# Generated by Django 4.2.27 on 2026-02-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0002_foodentry_user_alter_foodentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='calories',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='quantity',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
