# Generated by Django 4.2.27 on 2026-02-04 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_tracker', '0003_remove_foodentry_calories_foodentry_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='name',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodentry',
            name='time',
            field=models.TimeField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
